const db = require("./index.js");
const Popular = require("./popular.js");
const best = [
  {
    title: " Choufli 7al ",
    year: "2018",
    release_date: "2023-07-14",
    imdb_id: "tt11779248",
    imdb_rating: "7.6",
    poster: "https://images.moviefit.me/t/o/275123-choufli-hal.jpg",
    vote_count: "0",
    popularity: "3.429",
    youtube_trailer_key: "88GFHzLr65s",
    rated: "PG-13",
    genres: ["Fantasy", "Family"],
    stars: ["Dennis Quaid", "Meagan Good", "Michael Ealy"],
    directors: ["Guy Ritchie"],
    countries: ["United States of America"],
    description:
      "Choufli Hal (arabe : شوفلي حل), littéralement Trouve-moi une solution, est une série télévisée humoristique tunisienne, en arabe tunisien en 135 épisodes de 40 minutes, diffusée du 4 octobre 2005 au 19 septembre 2009 sur Tunisie 7 durant le mois de ramadan1.",
    language: ["English"],
    comments: [],
  },
  {
    title: "El foundou ",
    year: "2018",
    release_date: "2023-07-14",
    imdb_id: "tt11779248",
    imdb_rating: "7.6",
    poster:
      "https://www.tunisienumerique.com/wp-content/uploads/2021/05/el-foundou-1200x1574.jpg",
    vote_count: "0",
    popularity: "3.429",
    youtube_trailer_key: "6cDsUzbTFCo",
    rated: "PG-13",
    genres: ["Fantasy", "Action"],
    stars: ["Dennis Quaid", "Meagan Good", "Michael Ealy"],
    directors: ["Guy Ritchie"],
    countries: ["United States of America"],
    description:
      "Tunisia Series full of action and drama written by Mohamed Elyes ben khoud the big actor",
    language: ["English"],
    comments: [],
  },
  {
    title: "Cloudy with a Chance of Meatballs ",
    year: "2018",
    release_date: "2023-07-14",
    imdb_id: "tt11779248",
    imdb_rating: "7.6",
    poster: "https://m.media-amazon.com/images/I/81MvVWP9jBL._AC_SL1500_.jpg",
    vote_count: "0",
    popularity: "3.429",
    youtube_trailer_key: "pUaKcFI4BZY",
    rated: "PG-13",
    genres: ["Fantasy", "Family"],
    stars: ["Dennis Quaid", "Meagan Good", "Michael Ealy"],
    directors: ["Guy Ritchie"],
    countries: ["United States of America"],
    description:
      "Cloudy with a Chance of Meatballs is an animated fantasy loosely based on the 1978 book of the same name. It tells the story of Flint Lockwood (voiced by Bill Hader), a young scientist trying to create the ultimate invention.",
    language: ["English"],
    comments: [],
  },
  {
    title: "We Can Be Heroes ",
    year: "2018",
    release_date: "2023-07-14",
    imdb_id: "tt11779248",
    imdb_rating: "7.6",
    poster:
      "https://upload.wikimedia.org/wikipedia/en/8/8b/We_Can_Be_Heroes_2020_film_poster.png",
    vote_count: "0",
    popularity: "3.429",
    youtube_trailer_key: "g9O2YTtdaZA",
    rated: "PG-13",
    genres: ["Fantasy", "Family"],
    stars: ["Dennis Quaid", "Meagan Good", "Michael Ealy"],
    directors: ["Guy Ritchie"],
    countries: ["United States of America"],
    description:
      "When alien invaders capture the Earth's superheroes, their kids must learn to work together to save their parents- and the planet. When alien invaders capture the Earth's superheroes, their kids must learn to work together to save their parents- and the planet.",
    language: ["English"],
    comments: [],
  },
  {
    title: "Marmaduke ",
    year: "2018",
    release_date: "2023-07-14",
    imdb_id: "tt11779248",
    imdb_rating: "7.6",
    poster:
      "https://s3.amazonaws.com/static.rogerebert.com/uploads/movie/movie_poster/marmaduke-2010/large_rjrOVa3zpRpMRvyoBl6G5j28pq.jpg",
    vote_count: "0",
    popularity: "3.429",
    youtube_trailer_key: "xGx6IhjoWqw",
    rated: "PG-13",
    genres: ["Fantasy", "Family"],
    stars: ["Dennis Quaid", "Meagan Good", "Michael Ealy"],
    directors: ["Guy Ritchie"],
    countries: ["United States of America"],
    description:
      "Marmaduke is a huge, obliviously reckless, dopey Great Dane who loves his owner Phil. Having left his home in Kansas to move to California, he is forced to adjust to his new surroundings.",
    language: ["English"],
    comments: [],
  },
  {
    title: "Nanny McPhee and the Big Bang",
    year: "2019",
    release_date: "2023-07-14",
    imdb_id: "tt11779248",
    imdb_rating: "7.6",
    poster:
      "https://m.media-amazon.com/images/M/MV5BMTI5NDUxNDU4OF5BMl5BanBnXkFtZTcwNDk1NjM1Mw@@._V1_.jpg",
    vote_count: "0",
    popularity: "3.429",
    youtube_trailer_key: "54xMw6eouOM",
    rated: "PG-13",
    genres: ["Fantasy", "Family"],
    stars: ["Dennis Quaid", "Meagan Good", "Michael Ealy"],
    directors: ["Guy Ritchie"],
    countries: ["United States of America"],
    description:
      "Nanny McPhee & The Big Bang is set against a backdrop of English pastoral bliss, with hard-working Mrs Green (Gyllenhaal) struggling to cope with her three young children while her husband is away at war.",
    language: ["English"],
    comments: [],
  },
  {
    title: "Aladdin",
    year: "2019",
    release_date: "2023-07-14",
    imdb_id: "tt11779248",
    imdb_rating: "5.6",
    poster:
      "https://m.media-amazon.com/images/M/MV5BY2Q2NDI1MjUtM2Q5ZS00MTFlLWJiYWEtNTZmNjQ3OGJkZDgxXkEyXkFqcGdeQXVyNTI4MjkwNjA@._V1_SX300.jpg",
    vote_count: "0",
    popularity: "3.429",
    youtube_trailer_key: "foyufD52aog",
    rated: "PG-13",
    genres: ["Fantasy", "Family", "Adventure"],
    stars: ["Dennis Quaid", "Meagan Good", "Michael Ealy"],
    directors: ["Guy Ritchie"],
    countries: ["United States of America"],
    description:
      "Aladdin, a street urchin in the Arabian city of Agrabah, and his monkey Abu meet Princess Jasmine, who has snuck away from her sheltered life in the palace. Jasmine wishes to succeed her father as Sultan, but is instead expected to marry one of her royal suitors, including the charming yet dimwitted Prince Anders.",
    language: ["English"],
    comments: [],
  },
  {
    title: "Bad Blood",
    year: "2017",
    release_date: "07 Dec 2018",
    poster:
      "https://m.media-amazon.com/images/M/MV5BMzRmNzZkMmMtMzU5YS00ZThhLWE2YzItZTNhNGMwMmI1MjQyXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg",
    imdb_id: "tt5795144",
    imdb_rating: "6.8",
    vote_count: "90",
    popularity: "7.913",
    youtube_trailer_key: "8JbZKsfgXq0",
    genres: ["Crime"],
    stars: ["Jennifer Lawrence", "Mike Gassaway"],
    directors: ["Adam McKay"],
    countries: ["Germany", "Italy"],
    description:
      "A classic werewolf flick with an amphibious twist; it's a race against time to find the antidote. A classic werewolf flick with an amphibious twist; it's a race against time to find the antidote. A classic werewolf flick with an amphibious twist; it's a race against time to find the antidote.",
    language: ["English"],
    comments: [],
  },
  {
    title: "Jurassic World: Dominion",
    year: "2022",
    release_date: "2022-06-09",
    imdb_id: "tt8041270",
    imdb_rating: "7.29167",
    vote_count: "48",
    poster:
      "https://m.media-amazon.com/images/M/MV5BMDhkODhmZjEtMmE5My00MTE1LTllZGItMDkwOTZlMjY1ZWUyXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_SX300.jpg",
    popularity: "32.399",
    youtube_trailer_key: "LLFSNWU8yx8",
    rated: "Action, Adventure, Sci-Fi ",
    runtime: 90,
    genres: ["Adventure", "Action", "Sci-Fi", "Thriller"],
    stars: [
      "Chris Pratt",
      "Bryce Dallas Howard",
      "Laura Dern",
      "Jeff Goldblum",
      "Mamoudou Athie",
      "Scott Haze",
      "Dichen Lachman",
      "Sam Neill",
      "Daniella Pineda",
      "Campbell Scott",
    ],
    directors: ["Colin Trevorrow"],
    countries: ["United States of America"],
    description:
      "A new theme park, built on the original site of Jurassic Park, creates a genetically modified hybrid dinosaur, the Indominus Rex, which escapes containment and goes on a killing spree. Twenty-two years after the original Jurassic Park failed, the new park, also known as Jurassic World, is open for business.",
    language: ["English"],
    comments: [],
  },
  {
    title: "The Bad Guys",
    year: "2022",
    release_date: "2022-04-08",
    imdb_id: "tt8115900",
    imdb_rating: "0",
    vote_count: "0",
    poster:
      "https://m.media-amazon.com/images/M/MV5BOTlhNmVjOWMtNzNjNC00OTY0LWEyODUtY2Q4NDhiNTgzZDE2XkEyXkFqcGdeQXVyODk1MjAxNzQ@._V1_.jpg",
    popularity: "4.193",
    youtube_trailer_key: "chlHZJlTQ7E",
    rated: "Animation, Action, Comedy ",
    runtime: 90,
    genres: ["Animation", "Action", "Comedy"],
    stars: ["Sam Rockwell", "Craig Robinson", "Awkwafina", "Marc Maron"],
    directors: [
      "Pierre Pierfel",
      "Roger Allers",
      "Pierre Perifel",
      "2 more credits",
    ],
    countries: ["United States of America"],
    description:
      "An unfeeling gangster seeks to ruin the life of a young girl who rejected him. He forces her into prostitution and spies on her regularly, then he soon begins to fall for her.An unfeeling gangster seeks to ruin the life of a young girl who rejected him.",
    language: ["English"],
    comments: [],
  },
  {
    title: "Last Looks",
    year: "2020",
    release_date: "2021-12-31",
    imdb_id: "tt9244554",
    poster:
      "https://m.media-amazon.com/images/M/MV5BNWZkNGYzZDItMDg0Yy00NzBmLTg0MzEtMGJmNTQzYTllMDExXkEyXkFqcGdeQXVyMTA0Njg1ODU2._V1_SX300.jpg",
    imdb_rating: "5",
    vote_count: "0",
    youtube_trailer_key: "18YolVgfasM",
    genres: ["Action", "Crime", "Thriller"],
    stars: [
      "Charlie Hunnam",
      "Mel Gibson",
      "Eiza González",
      "Clancy Brown",
      "Rupert Friend",
      "Lucy Fry",
      "Dominic Monaghan",
      "Jacob Scipio",
      "Paul Ben-Victor",
      "Method Man",
      "Morena Baccarin",
    ],
    directors: ["Tim Kirkby"],
    countries: ["United States of America"],
    description:
      "A disgraced ex-cop seeks solace by moving to the woods, but his quiet life comes to an end when a private eye recruits him to investigate a murder. A disgraced ex-cop seeks solace by moving to the woods, but his quiet life comes to an end when a private eye recruits him to investigate a murder. ",
    language: ["English"],
    comments: [],
  },
  {
    title: "Sherlock Holmes 3",
    year: "2021",
    release_date: "2021-12-24",
    imdb_id: "tt2094116",
    imdb_rating: "8.25843",
    poster:
      "https://assets1.ignimgs.com/2018/05/08/sherlock-holmes-1525788622970.jpg?width=300",
    youtube_trailer_key: "s1s-XbvncNg",
    rated: "5.5",
    genres: ["Mystery", "Action", "Crime", "Adventure"],
    stars: [
      "Robert Downey Jr.",
      "Jude Law",
      "Jared Harris",
      "Eddie Marsan",
      "Rachel McAdams",
    ],
    directors: ["Dexter Fletcher"],
    countries: ["United States of America"],
    language: ["English"],
    comments: [],
  },
  {
    title: "Submission",
    year: "2019",
    release_date: "2019-09-19",
    poster:
      "https://m.media-amazon.com/images/M/MV5BN2M4NzAyOTgtZTUxYi00MjRjLTk1ZjgtNTI5YThkYWE2OWViXkEyXkFqcGdeQXVyMjg5OTIyMDk@._V1_.jpg",
    imdb_id: "tt4824256",
    imdb_rating: "7.1",
    youtube_trailer_key: "P11MroggtPo",
    genres: ["Drama", "Sport"],
    stars: [
      "Scott Pryor",
      "Darrin Henson",
      "Eric Roberts",
      "Lorynn York",
      "Kevin Sizemore",
      "Sara McMann",
      "Lunden De'Leon",
      "Ovince Saint Preux",
      "John Gray",
      "Adam Minarovich",
      "Lauren York",
      "Darrin Dewitt Henson",
      "Dixie Light",
      "Lawrence Gilligan",
      "Micah Pryor",
      "Danny Williams-Lopez",
      "J Randall",
    ],
    directors: ["J.M. Berrios"],
    countries: ["United States of America", "USA"],
    description:
      "A cynical college professor takes a keen interest in a talented young writing student. A cynical college professor takes a keen interest in a talented young writing student. A cynical college professor takes a keen interest in a talented young writing student.",
    language: ["English", "en"],
    comments: [],
  },
  {
    title: "The Nightingale",
    year: "2022",
    release_date: "2022-12-23",
    imdb_rating: "6.79167",
    poster:
      "https://m.media-amazon.com/images/M/MV5BNjVmZmY1NmQtMWNhZS00ZDUwLTk5ZTQtZGE4NWIyM2YwMDRiXkEyXkFqcGdeQXVyODY3Nzc0OTk@._V1_SX300.jpg",
    youtube_trailer_key: "YuP8g_GQIgI",
    rated: "6.6",
    genres: ["Drama", "History", "War"],
    stars: ["Elle Fanning", "Dakota Fanning"],
    directors: ["Mélanie Laurent", "Michelle MacLaren"],
    countries: ["United States of America", "USA"],
    description:
      "The Nightingale is a 2018 Australian drama film written, directed, and co-produced by Jennifer Kent. Set in 1825 in the penal colony of Van Diemen's Land (present-day Tasmania), the film follows a young female convict seeking revenge for a terrible act of violence committed against her family.",
    language: ["English", "N/A"],
    comments: [],
  },
  {
    title: "Kung Fury",
    year: "2020",
    imdb_rating: "8.875",
    vote_count: "8",
    poster:
      "https://m.media-amazon.com/images/M/MV5BMjQwMjU2ODU5NF5BMl5BanBnXkFtZTgwNTU1NjM4NTE@._V1_SX300.jpg",
    popularity: "2.435",
    youtube_trailer_key: "nO_DIwuGBnA",
    rated: "Action, Comedy, Crime",
    genres: [
      "Action",
      "Comedy",
      "Sci-Fi",
      "Fantasy",
      "Crime",
      "Science Fiction",
    ],
    stars: [
      "David Sandberg",
      "Michael Fassbender",
      "Arnold Schwarzenegger",
      "David Hasselhoff",
      "Leopold Nilsson",
      "Eleni Young",
      "Alexandra Shipp",
      "Anton Kottas",
      "Jorma Taccone",
      "Max Kraus",
    ],
    directors: ["David Sandberg"],
    countries: ["Sweden", "United States of America"],
    description:
      "In 1985, Kung Fury, the toughest martial artist cop in Miami, goes back in time to kill the worst criminal of all time - Kung Führer, a.k.a. Adolf Hitler. ... Kung Fury decides to travel back in time, to Nazi Germany, in order to kill Hitler and end the Nazi empire once and for all.",
    language: ["English", "Deutsch", "svenska", "English, German, Swedish"],
    comments: [],
  },
  {
    title: "A Mother's Crime",
    year: "2017",
    release_date: "2017-08-21",
    imdb_id: "tt7444708",
    imdb_rating: "6.8",
    poster:
      "https://m.media-amazon.com/images/M/MV5BM2FkZmI4ZWYtNTZlYy00YjBlLWE1OWItNjNlOTQ3ZGQ0NTMxXkEyXkFqcGdeQXVyNzY4ODc3OTA@._V1_SX300.jpg",
    youtube_trailer_key: "2TxoDMfZudM",
    genres: ["Thriller", "TV Movie"],
    stars: [
      "Jenny Gabrielle",
      "April Bowlby",
      "Amber Lynn Ashley",
      "Ryan Jason Cook",
      "J.D. Garfield",
      "Allyson Harbert",
      "Matt Page",
      "Brytnee Ratledge",
      "Matthew Van Wettering",
      "Arina Gancicova",
    ],
    directors: ["Farhad Mann", "Lora Martinez-Cunningham", "Amber LeRae Earls"],
    countries: ["United States of America", "USA"],
    description:
      "Found guilty of murder, a woman is forced to give custody of her infant daughter to her biggest rival, her own sister. Now, released from prison, she'll stop at nothing to get her daughter back.",
    language: ["English"],
    comments: [],
  },
  {
    title: "The Intruder",
    year: "2019",
    release_date: "2019-05-03",
    imdb_id: "tt6722030",
    imdb_rating: "6.2",
    poster:
      "https://m.media-amazon.com/images/M/MV5BNTczMzc4NDY0MF5BMl5BanBnXkFtZTgwMjI3Njg3NjM@._V1_SX300.jpg",
    vote_count: "297",
    popularity: "19.372",
    youtube_trailer_key: "aKXvex7b1Ew",
    rated: "PG-13",
    genres: ["Thriller", "Drama", "Horror", "Mystery"],
    stars: [
      "Dennis Quaid",
      "Meagan Good",
      "Michael Ealy",
      "Joseph Sikora",
      "Alvina August",
      "Lili Sepe",
      "Kurt Evans",
      "Debs Howard",
      "Lee Shorten",
      "Carolyn Anderson",
      "Erica Cerra",
      "Raylene Harewood",
      "Caroline Muthoni Muita",
      "Connor Mackay",
      "John Torrance",
      "Mary Elise Torrance",
    ],
    directors: ["Deon Taylor"],
    countries: ["United States of America"],
    description:
      "When a young married couple (Michael Ealy and Meagan Good) buys their dream house in the Napa Valley, they think they have found the perfect home to take their next steps as a family. But when the strangely attached seller (Dennis Quaid) continues to infiltrate their lives, they begin to suspect that he has hidden motivations beyond a quick sale.",
    language: ["English", "en"],
    comments: [],
  },
  {
    title: "A Quiet Life",
    year: "2010",
    release_date: "2010-11-05",
    imdb_id: "tt1521090",
    imdb_rating: "6.5",
    poster: "https://upload.wikimedia.org/wikipedia/en/e/e2/A_Quiet_Life.jpg",
    vote_count: "90",
    popularity: "7.913",
    youtube_trailer_key: "0gZD-beTuZo",
    genres: ["Drama", "Crime"],
    stars: [
      "Toni Servillo",
      "Marco D'Amore",
      "Francesco Di Leva",
      "Juliane Köhler",
      "Leonardo Sprengler",
      "Alice Dwyer",
      "Maurizio Donadoni",
      "Micki Bertling",
      "Ulrich Cyran",
      "Nick Dong-Sik",
      "Joachim Kretzer",
      "Giovanni Ludeno",
      "Edoardo Melone",
      "Franco Melone",
      "Daniel Roesner",
      "Enzo Salomone",
      "Lucia Schlör",
      "Hildburg Schmidt",
      "Andreas Wellano",
      "Hans-Joachim Heist",
      "Irmtraud Hetz",
      "Peter Sablic",
      "Yalcin Bögürkü",
      "Tina Klein",
      "Frank M. Ahearn",
      "Eilean Roland",
    ],
    directors: ["Claudio Cupellini"],
    countries: ["Germany", "Italy", "France", "Italy, France, Germany"],
    description:
      "An alternative perspective on migration depicted through a gallery of portraits of a not so quiet daily life in Kavala, a small town in Northern Greece. An ageing local community juxtaposed with a young refugee family residing in the town because of a distant war. While silently contemplating on the past and patiently waiting for the future to come, they are all living a normal, seemingly quiet life.",
    language: [
      "Deutsch",
      "English",
      "Italiano",
      "Italian, German, Neapolitan, English",
    ],
    comments: [],
  },

  {
    title: "In Your Arms",
    year: "2009",
    release_date: "2009-07-01",
    imdb_id: "tt1320372",
    imdb_rating: "5.8",
    poster:
      "https://m.media-amazon.com/images/M/MV5BMGExZjNhNTktMTAxOS00MjRmLTk3NTgtZGEyMjViOTEyM2Q3XkEyXkFqcGdeQXVyMjkyNDY5Mzc@._V1_.jpg",
    vote_count: "43",
    popularity: "0.6",
    youtube_trailer_key: "7VSdFCH2VUo",
    genres: ["Drama"],
    stars: [
      "Michèle Laroque",
      "Martin Loizillon",
      "Lola Naymark",
      "Catherine Mouchet",
      "Marc Bertolini",
      "Marie-Bénédicte Roy",
      "Mélanie Leray",
      "Mariana Ramos",
      "Antonio Ramos",
      "Salvador Douezy",
      "Bonnafet Tarbouriech",
      "Julien De Almeida",
    ],
    directors: ["Hubert Gillet"],
    countries: ["France"],
    description:
      " After We Collided is a 2020 American romantic drama film directed by Roger Kumble and written by Anna Todd and Mario Celaya. It is based on the 2014 new adult fiction novel of the same name by Todd, and is the sequel to After (2019). The film stars Josephine Langford and Hero Fiennes Tiffin as Tessa Young and Hardin Scott, respectively, with Dylan Sprouse, Shane Paul McGhie, Candice King, Khadijha Red Thunder, Inanna Sarkis, Samuel Larsen, and Selma Blair in supporting roles.",
    language: ["Français", "French"],
    comments: [],
  },
  {
    title: "The Three Wise Men",
    year: "2020",
    release_date: "2020-11-27",
    imdb_id: "tt13319946",
    imdb_rating: "7.5",
    poster:
      "https://m.media-amazon.com/images/M/MV5BYzk3NjZmZWMtN2YyYS00ZThhLTk4YjEtYmFkNDk3ZTA1NDA4XkEyXkFqcGdeQXVyODMyNDE3MTI@._V1_SX300.jpg",
    vote_count: "2",
    popularity: "2.168",
    youtube_trailer_key: "dyJJv-n4xoE",
    genres: ["Family", "History", "Action", "Short"],
    stars: ["Andy Griffith"],
    directors: ["Yarrow Cheney", "Carrie Cheney"],
    countries: ["United States of America"],
    description:
      "Narrated by the legendary Andy Griffith (THE ANDY GRIFFITH SHOW, MATLOCK), this heartwarming animated special is a charming re-imagination of the classic Christmas story following the three wise men on a wondrous quest to meet the newborn king. Their journey is told through rhymed narration alongside a soundtrack of holiday carols performed by The Brothers Cazimero from Hawaii and the new original song Noel by the Grammy Award-winning songwriter Jonas Myrin.",
    language: ["English", "en"],
    comments: [],
  },
  {
    title: "People You May Know",
    year: "2016",
    release_date: "2016-07-07",
    imdb_id: "tt4696310",
    imdb_rating: "5.7",
    poster:
      "https://m.media-amazon.com/images/M/MV5BMjZkZTU0ODktYjhjNi00YWNlLTljYjgtOTBjNzZjZGMxMDVlXkEyXkFqcGdeQXVyMjQ3NzUxOTM@._V1_SX300.jpg",
    vote_count: "19",
    popularity: "3.72",
    youtube_trailer_key: "wOVZb_jJ0_g",
    genres: ["Comedy", "Drama"],
    stars: [
      "Sean Maher",
      "Andrea Grano",
      "Mark Cirillo",
      "Lauren C. Mayhew",
      "Nacho San José",
      "Curt Hansen",
      "Trey McCurley",
      "Jimmy Shaw",
      "Nelly Castillo",
      "Deborah Domínguez",
      "Tara Karsian",
      "Frederick Keeve",
      "David Krohnert",
      "Connor Linnerooth",
      "Louis Macarthur",
      "Sergio Macian",
      "Carmen Maura",
      "Rafael I. Molina",
      "Raymond Rivera III",
      "Amor Sanchez",
      "Karl Schott",
      "Isabel Serrano",
      "Nikos Siozos",
      "David Vega",
      "Cynthia Webster",
      "Jessica B. Wellington",
    ],
    directors: ["J.C. Falcón"],
    countries: ["USA, Spain"],
    description:
      "Joe, Delia, Rodrigo, and Herbert are very close friends in their mid 30’s. Delia and Rodrigo are married, while Joe is Delia’s ex-boyfriend who turned out to be gay. After a night of drinking, Joe and Delia sleep together and she gets pregnant. Meanwhile, Joe is in a secret online relationship with Tom. They have not met in person yet... and they never will.",
    language: ["English"],
    comments: [],
  },
  {
    title: "Blood Moon River",
    year: "2017",
    release_date: "2017-04-22",
    imdb_id: "tt5925370",
    imdb_rating: "2",
    poster:
      "https://m.media-amazon.com/images/M/MV5BMTc1NDg4YWMtZDdlMS00NTdlLTljZDQtNGRkZTIxZTZlNTI4XkEyXkFqcGdeQXVyMTU5MjIyMTI@._V1_SX300.jpg",
    vote_count: "1",
    youtube_trailer_key: "St3J3GHEDNA",
    genres: ["Horror"],
    stars: [
      "Daniel Murphy",
      "Tom Komisar",
      "Jack Norman",
      "R.J. Cecott",
      "Rebekah Erb",
      "Sydney Dean",
      "Tony Walters",
      "Cameron Scott",
      "Lindsey McIntire",
      "Edward Diersen",
      "Stan Traylor",
      "James Michael",
      "Naphatia St Pierre",
      "Sara Ingram",
      "Eric Reaume",
      "Cara McConnell",
      "Linda Schrader",
    ],
    directors: ["R.J. Cecott", "Tom Komisar", "Daniel Murphy"],
    countries: ["United States of America"],
    description:
      "A group of friends try to debunk a local legend, but have they bitten off more than they can chew?",
    language: ["English", "en"],
    comments: [],
  },
  {
    title: "Submission",
    year: "2019",
    release_date: "2019-09-19",
    imdb_id: "tt4824256",
    poster:
      "https://m.media-amazon.com/images/M/MV5BN2M4NzAyOTgtZTUxYi00MjRjLTk1ZjgtNTI5YThkYWE2OWViXkEyXkFqcGdeQXVyMjg5OTIyMDk@._V1_.jpg",
    imdb_rating: "7.1",
    youtube_trailer_key: "P11MroggtPo",
    genres: ["Drama", "Sport"],
    stars: [
      "Scott Pryor",
      "Darrin Henson",
      "Eric Roberts",
      "Lorynn York",
      "Kevin Sizemore",
      "Sara McMann",
      "Lunden De'Leon",
      "Ovince Saint Preux",
      "John Gray",
      "Adam Minarovich",
      "Lauren York",
      "Darrin Dewitt Henson",
      "Dixie Light",
      "Lawrence Gilligan",
      "Micah Pryor",
      "Danny Williams-Lopez",
      "J Randall",
    ],
    directors: ["J.M. Berrios"],
    countries: ["United States of America", "USA"],
    description:
      "A cynical college professor takes a keen interest in a talented young writing student.",
    language: ["English", "en"],
    comments: [],
  },
  {
    title: "Soldier of Fortune",
    year: "1955",
    release_date: "1955-01-01",
    imdb_id: "tt0048640",
    imdb_rating: "5.6",
    poster:
      "https://m.media-amazon.com/images/M/MV5BNDcyYzA2NGItYzNlOS00NzY0LWEzZmUtMzIxYjQxNWYzODRkXkEyXkFqcGdeQXVyNTU3MTY2Mg@@._V1_SX300.jpg",
    youtube_trailer_key: "Ye_XCOoAdxU",
    genres: ["Adventure", "Drama", "Action", "Romance", "Crime", "Thriller"],
    stars: [
      "Clark Gable",
      "Susan Hayward",
      "Michael Rennie",
      "Gene Barry",
      "Tom Tully",
      "Alexander D'Arcy",
      "Anna Sten",
      "Leo Gordon",
      "Jack Kruschen",
      "James Hong",
    ],
    directors: ["Edward Dmytryk"],
    countries: ["United States of America", "USA"],
    description:
      "IN THEATERS & ON DEMAND AUGUST 3rd! A former US special forces soldier is reluctantly appointed to protect a group of millionaires who want to experience the thrills of war first-hand. But when their excursion goes horribly awry, the unlikely team must band together in order to get out alive. Starring Christian Slater, Ving Rhames, Dominic Monaghan, Sean Bean and James Cromwell.",
    language: ["English", "en"],
    comments: [],
  },
  {
    title: "Red Sun",
    year: "1971",
    release_date: "1971-09-15",
    imdb_id: "tt0067770",
    imdb_rating: "6.8",
    poster:
      "https://m.media-amazon.com/images/M/MV5BNTMwNDgyNDItOTYzZi00MjhmLTgyYzItYjNiY2Y5NGY2YWY4XkEyXkFqcGdeQXVyMjQwMjk0NjI@._V1_SX300.jpg",
    youtube_trailer_key: "r1iC4ids4v8",
    genres: ["Western", "Action"],
    stars: [
      "Charles Bronson",
      "Ursula Andress",
      "Toshirō Mifune",
      "Alain Delon",
      "Capucine",
      "Barta Barri",
      "Guido Lollobrigida",
      "Anthony Dawson",
      "Gianni Medici",
      "Georges Lycan",
      "Luc Merenda",
      "Tetsu Nakamura",
    ],
    directors: [
      "Terence Young",
      "Joan Davis",
      "Ricardo Huertas Frutos",
      "Christian Raoux",
      "Ricardo Huertas",
    ],
    countries: ["France", "Italy", "Spain", "France, Italy, Spain"],
    description:
      "The story takes place in Arizona, around 1870. Link and Gotch are two ruthless robbers that attack along with their men at the train which carries the ambassador of Japan over to Washington. During the robbery, Gotch takes a very valuable gold sword, which is a gift from the emperor to the president of the U.S. and tries to kill Link, so that he can take all the money for himself.",
    language: ["Español", "English", "日本語", "English, Spanish, Japanese"],
    comments: [],
  },
  {
    title: "A Mother's Crime",
    year: "2017",
    release_date: "2017-08-21",
    imdb_id: "tt7444708",
    imdb_rating: "6.8",
    poster:
      "https://m.media-amazon.com/images/M/MV5BM2FkZmI4ZWYtNTZlYy00YjBlLWE1OWItNjNlOTQ3ZGQ0NTMxXkEyXkFqcGdeQXVyNzY4ODc3OTA@._V1_SX300.jpg",
    youtube_trailer_key: "2TxoDMfZudM",
    genres: ["Thriller", "TV Movie"],
    stars: [
      "Jenny Gabrielle",
      "April Bowlby",
      "Amber Lynn Ashley",
      "Ryan Jason Cook",
      "J.D. Garfield",
      "Allyson Harbert",
      "Matt Page",
      "Brytnee Ratledge",
      "Matthew Van Wettering",
      "Arina Gancicova",
    ],
    directors: ["Farhad Mann", "Lora Martinez-Cunningham", "Amber LeRae Earls"],
    countries: ["United States of America", "USA"],
    description:
      "Encouraged by her lover, Danielle kills her husband and goes on the lam with her infant daughter Cali. But the cops catch her and, en route to prison, she agrees to give custody of Cali to her arch rival, her sister Nikki. But on release from prison, Danielle will stop at nothing to get Cali back from Nikki's safe and healthy home.",
    language: ["English"],
    comments: [],
  },
  {
    title: "Tarung Sarung",
    year: "2020",
    release_date: "2020-12-31",
    imdb_id: "tt11749980",
    imdb_rating: "7.3",
    poster:
      "https://m.media-amazon.com/images/M/MV5BZWM4ZmNhMjctNTA1Ni00MzVjLWJiOTQtYTUwNTY4ZGQwZmRlXkEyXkFqcGdeQXVyNzEzNjU1NDg@._V1_SX300.jpg",
    vote_count: "5",
    youtube_trailer_key: "AgaXQPJCRjA",
    genres: ["Action", "Drama", "Adventure"],
    stars: [
      "Panji Zoni",
      "Yayan Ruhian",
      "Maizura",
      "Cemal Faruk",
      "Surya Saputra",
      "Jarot SuperDJ",
      "Doyok SuperDJ",
      "Annette Edoarda",
      "Imelda Therinne",
      "Hajra Romessa",
    ],
    directors: ["Archie Hekagery"],
    countries: ["Indonesia"],
    description:
      "Wealthy and spoiled, a young man finds something to fight for when he falls in love with an environment activist protesting his family's business. Wealthy and spoiled, a young man finds something to fight for when he falls in love with an environment activist protesting his family's business.",
    language: ["Bahasa indonesia"],
    comments: [],
  },
  {
    title: "Harry and Walter Go to New York",
    year: "1976",
    release_date: "1976-06-17",
    imdb_id: "tt0074608",
    imdb_rating: "6.4",
    poster:
      "https://m.media-amazon.com/images/M/MV5BYzVhMGJjNTUtYzg2Ny00OTU5LTgwYWQtZjlkNTcwMTJiZDJkL2ltYWdlXkEyXkFqcGdeQXVyMjI4MjA5MzA@._V1_SX300.jpg",
    vote_count: "5",
    youtube_trailer_key: "-ZDvhYsm2as",
    genres: ["Crime", "Comedy"],
    stars: [
      "Elliott Gould",
      "James Caan",
      "Diane Keaton",
      "Michael Caine",
      "Charles Durning",
      "Lesley Ann Warren",
      "Val Avery",
      "Jack Gilford",
      "Dennis Dugan",
      "Carol Kane",
    ],
    directors: ["Mark Rydell"],
    countries: ["United States of America"],
    description:
      "In the film, two down-on-their-luck con men try to pull off the biggest heist ever seen in late nineteenth-century New York City. They are opposed by the greatest bank robber of the day, and by a crusading newspaper editor.",
    language: ["Español", "Deutsch", "English"],
    comments: [],
  },
  {
    title: "Harry and Walter Go to New York",
    year: "1988",
    release_date: "1988-12-23",
    imdb_id: "tt0143952",
    imdb_rating: "3.8",
    poster:
      "https://m.media-amazon.com/images/M/MV5BNTliYThhZDEtNThkOS00NjZjLWE0ODktN2FiZmQ1YTg2NTkzXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
    vote_count: "5",
    youtube_trailer_key: "kk5WdVQj9Ro",
    genres: ["Drama", "Horror", "Thriller"],
    stars: [
      "Alex Kubik",
      "Elizabeth Kent",
      "Cameron Mitchell",
      "Mark Witsken",
      "Sullivan Hester",
      "Michael Nash",
      "Laura Kalison",
      "Paul Dean",
      "Jay Leggett",
      "Randolph Powell",
    ],
    directors: ["Leszek Burzynski"],
    countries: ["United States of America"],
    description:
      "In the film, two down-on-their-luck con men try to pull off the biggest heist ever seen in late nineteenth-century New York City. They are opposed by the greatest bank robber of the day, and by a crusading newspaper editor.",

    language: ["English"],
    comments: [],
  },
  {
    title: "Shopping",
    year: "1994",
    release_date: "1994-12-06",
    imdb_id: "tt0111173",
    imdb_rating: "5.8",
    poster:
      "https://m.media-amazon.com/images/M/MV5BNjVlN2MzYTYtNzEyMy00YTI0LWFiMGYtZmJmOTBhZDgzYTM5XkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_SX300.jpg",
    vote_count: "5",
    youtube_trailer_key: "cR1Zvw5MmLs",
    genres: ["Action", "Adventure", "Drama", "Sci-Fi", "Thriller", "Crime"],
    stars: [
      "Sadie Frost",
      "Jude Law",
      "Sean Pertwee",
      "Fraser James",
      "Sean Bean",
      "Marianne Faithfull",
      "Jonathan Pryce",
      "Ralph Ineson",
      "Eamonn Walker",
      "Lee Whitlock",
    ],
    directors: ["Paul W. S. Anderson"],
    countries: ["United Kingdom", "UK, Japan"],
    description:
      "Shopping is a 2013 New Zealand coming-of-age film written and directed by Mark Albiston and Louis Sutherland. It stars Kevin Paulo as a mixed race Samoan New Zealander who falls in with a group of shoplifters led by an Eastern-European immigrant played by Jacek Koman.",
    language: ["English"],
    comments: [],
  },
  {
    title: "Robot & Frank",
    year: "2012",
    release_date: "2012-08-16",
    imdb_id: "tt1990314",
    imdb_rating: "6.9",
    poster:
      "https://m.media-amazon.com/images/M/MV5BMTUzMTE0NTk4Ml5BMl5BanBnXkFtZTcwNjQ1OTMwOA@@._V1_.jpg",
    vote_count: "5",
    youtube_trailer_key: "a_gAJk_CfPI",
    genres: ["Action", "Comedy", "Drama", "Sci-Fi", "Sci-Fi", "Crime"],
    stars: [
      "Frank Langella",
      "Liv Tyler",
      "James Marsden",
      "Susan Sarandon",
      "Peter Sarsgaard",
      "Jeremy Strong",
      "Jeremy Sisto",
      "Bonnie Bentley",
      "Dario Barosso",
      "Rachael Ma",
    ],
    directors: ["Jake Schreier"],
    countries: ["United States of America"],
    description:
      "A retired burglar and a household appliance. Robot & Frank tells the story of relationship between a retired burglar and a household appliance more relentless than an alarm clock. Frank is a man who lives alone in a bucolic house in upstate New York and is somewhere along the slope into dementia.",
    language: ["English"],
    comments: [],
  },
  {
    title: "Koch Brothers Exposed",
    year: "2012",
    release_date: "2012-03-07",
    imdb_id: "tt2347411",
    imdb_rating: "6.5",
    poster:
      "https://m.media-amazon.com/images/M/MV5BMTM3NDQ2MDQwMV5BMl5BanBnXkFtZTcwNjUxMDc3Nw@@._V1_SX300.jpg",
    vote_count: "5",
    youtube_trailer_key: "zc_3wsLd01s",
    genres: ["Documentary"],
    stars: [
      "Bernie Sanders",
      "Van Jones",
      "Bill McKibben",
      "Jim Hightower",
      "Katrina vanden Heuvel",
      "Charles G. Koch",
      "David H. Koch",
      "Fred C. Koch",
      "Lawrence Lessig",
      "Ben Jealous",
    ],
    directors: ["Robert Greenwald"],
    countries: ["United States of America"],
    description:
      "Koch Brothers Exposed is a 2012 U.S. documentary, compiled by liberal political activist and filmmaker Robert Greenwald from a viral video campaign produced by Brave New Films, about the alleged political activities of the Koch brothers.",
    language: ["English"],
    comments: [],
  },
  {
    title: "L.A. Superheroes",
    year: "2013",
    release_date: "2013-11-08",
    imdb_id: "tt2515476",
    imdb_rating: "7.5",
    poster:
      "https://m.media-amazon.com/images/M/MV5BMTM4MzYxNTUxMV5BMl5BanBnXkFtZTcwNzA3MDY0OQ@@._V1_SX300.jpg",
    vote_count: "5",
    youtube_trailer_key: "U596XawbqX0",
    genres: ["Comedy", "Drama"],
    stars: [
      "Yelena Popovic",
      "Alexander Zisiades",
      "Craig Archibald",
      "Alejandra Bursik-Cervantes",
      "Catherine Carlen",
      "T.J. Castronovo",
      "Tsulan Cooper",
    ],
    directors: ["Yelena Popovic", "Alexandros Potter"],
    countries: ["United States of America"],
    language: ["English"],
    comments: [],
  },
  {
    title: "Uninhabited",
    year: "2010",
    release_date: "2010-05-14",
    imdb_id: "tt1459013",
    imdb_rating: "4.4",
    poster:
      "https://m.media-amazon.com/images/M/MV5BMjE2NjIyNTgxNF5BMl5BanBnXkFtZTcwODE4Njc3Mw@@._V1_SX300.jpg",
    vote_count: "5",
    youtube_trailer_key: "gdmg5nm2iCM",
    genres: ["Thriller", "Horror"],
    stars: [
      "Geraldine Hakewill",
      "Bob Baines",
      "Tasia Zalar",
      "Henry James",
      "Billy Milionis",
      "Terry Siourounis",
    ],
    directors: ["Bill Bennett"],
    countries: ["Australia"],
    description:
      "A young couple go to a remote and deserted coral island for a camping holiday, only to find that the island is inhabited by a ghost seeking retribution for a past outrage.",
    language: ["English", "Deutsch"],
    comments: [],
  },
  {
    title: "Alpha Dog",
    year: "2006",
    release_date: "2006-01-27",
    imdb_id: "tt0426883",
    imdb_rating: "6.7",
    poster:
      "https://m.media-amazon.com/images/M/MV5BMjExODMyNzQzMl5BMl5BanBnXkFtZTYwNzMwNTg3._V1_SX300.jpg",
    vote_count: "5",
    youtube_trailer_key: "SPbwocBe_tQ",
    genres: ["Crime", "Drama", "History", "Thriller", "Action"],
    stars: [
      "Emile Hirsch",
      "Bruce Willis",
      "Amanda Seyfried",
      "Justin Timberlake",
      "Shawn Hatosy",
      "Ben Foster",
      "Harry Dean Stanton",
      "Matthew Barry",
      "Fernando Vargas",
      "Vincent Kartheiser",
    ],
    directors: ["Nick Cassavetes", "Jeanne Byrd"],
    countries: ["United States of America", "Germany"],
    description:
      "Alpha Dog is a 2006 American crime drama film written and directed by Nick Cassavetes based on the true story of the kidnapping and murder of Nicholas Markowitz in 2000. It was first screened at the Sundance Film Festival on January 27, 2006, with a wide release the following year on January 12, 2007.",
    language: ["English", "Český", "Español"],
    comments: [],
  },
  {
    title: "My Friend, Tucker",
    year: "2019",
    release_date: "2019-03-03",
    imdb_id: "tt7972040",
    imdb_rating: "8.2",
    poster:
      "https://m.media-amazon.com/images/M/MV5BMDc2NzQ2NmUtMDI2NC00MzNjLWI3OGItODM1MGQwM2QxZGZkXkEyXkFqcGdeQXVyNTExNjA1MzE@._V1_SX300.jpg",
    vote_count: "5",
    youtube_trailer_key: "uApF4dWsUn0",
    genres: ["Comedy", "Drama"],
    stars: ["Avery Anthony", "Mitchell Edwards"],
    directors: ["Clarence Williams IV"],
    countries: ["United States of America"],
    description:
      "A troubled young man named Hamilton returns home for the first time in years since leaving for college and reconnects with his childhood best friend, Tucker. The two reflect on life, love, adulthood, and the ups and downs of childhood.",
    language: ["English"],
    comments: [],
  },
];
const insertBest = function () {
  Popular.create(best)
    .then(() => {
      console.log("Database seeded successfully");
    })
    .catch((error) => {
      console.log("error seeding the database: ", error);
    });
};
insertBest();
